agent_optimize_agent = dict(
    name="agent_optimize_agent",
    type="AgentOptimizeAgent",
    description="An agent that evolves a generated agent (Python class and/or HTML prompt) given an optimization task.",
    model_name="google/gemini-3.1-pro-preview",
    prompt_name="agent_optimize_agent",
    memory_name="file_system_memory",
    max_actions=10,
    max_step=30,
    max_token=1000000,
    timeout=1800,
    review_steps=5,
    enable_evolving=False,
    use_memory=False,
)
