environment_generate_agent = dict(
    name="environment_generate_agent",
    type="EnvironmentGenerateAgent",
    description="An agent that generates a new environment Python class and config dict from a description.",
    model_name="google/gemini-3.1-pro-preview",
    prompt_name="environment_generate_agent",
    memory_name="file_system_memory",
    max_actions=10,
    max_step=30,
    max_token=1000000,
    timeout=1800,
    review_steps=5,
    enable_evolving=False,
    use_memory=True,
)
