skill_optimize_agent = dict(
    name="skill_optimize_agent",
    type="SkillOptimizeAgent",
    description="An agent that evolves a skill's SKILL.md given an optimization task.",
    model_name="google/gemini-3.1-pro-preview",
    prompt_name="skill_optimize_agent",
    memory_name="file_system_memory",
    max_actions=10,
    max_step=30,
    max_token=1000000,
    timeout=1800,
    review_steps=5,
    enable_evolving=False,
    use_memory=False,
)
